#!/bin/bash

set -euo pipefail
cd "$(dirname "$0")/.."

pwd

./scripts/clean-generated
./scripts/build-docker-image
./scripts/build-assets
./scripts/build-game
./scripts/build-proxy
./scripts/build-web
./scripts/build-serve-image

echo "Build complete. You can now run ./scripts/serve to run the game server."