#!/bin/bash

set -euo pipefail
cd "$(dirname "$0")/.."

pwd

./scripts/build-docker-image
./scripts/build-assets
./scripts/build-game

echo "Build complete. You can now run ./scripts/serve to run the game server."