#!/bin/bash

set -euo pipefail
cd "$(dirname "$0")/.."

./scripts/build-docker-helper
./scripts/build-assets-docker
./scripts/build-game-docker

echo "Build complete. You can now run ./scripts/serve-docker to run the game server."